### ISSUE TITLE
Error thrown from worklet: "importScripts is not defined"

### ISSUE THREAD

**Issue by Nantris** [popelenkow/worker-url#8]
Any idea what might cause this? Or how one might work around this? Any insights you can give me however small would be greatly appreciated!

[I guess it should be built into the browser](https://github.com/pwa-builder/PWABuilder/issues/760#issuecomment-630252169) - so I'm not really sure what could cause it to be unavailable.

```
Uncaught ReferenceError: importScripts is not defined
    at Object.__webpack_require__.f.i (ourWorklet.dev.js:637:15)
    at ourWorklet.dev.js:111:40
    at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e (ourWorklet.dev.js:110:67)
    at Function.__webpack_require__.x (ourWorklet.dev.js:1121:40)
    at ourWorklet.dev.js:1129:57
    at ourWorklet.dev.js:1131:12
 ```

Thanks for the great work!

**Comment by Nantris** [comment]
Fwiw I was able to get it working without using the `worker-url` method of defining the `workletUrl`:

**Works**
```js
const workletUrl = new URL('myWorklet.js', import.meta.url);
await CSS.layoutWorklet.addModule(workletUrl);
```
